# espanso match file

#############
# IMPORTANT #: If using these snippets in vscode set "editor.acceptSuggestionOnCommitCharacter": false
#############

matches:
  # Paramterized forloops
  # https://espanso.org/docs/matches/regex-triggers/
  - regex: "each(?P<array>.*);"
    replace: "for ([key, value] of Object.entries({{array}})) {\n$|$}"
  - regex: "for(?P<idx>.)(?P<array>.*);"
    replace: "for(let {{idx}} = 0; {{idx}} < {{array}}.length; {{idx}}++){\n$|$}"

  # Static if/else
  - trigger: "if;"
    replace: "if($|$){\n$|$}else{\n}"

  # Static try/catch
  - trigger: "try;"
    replace: "try {\n}catch (error) {\nconsole.error(error)};"

  # Static logger
  - regex: "log(?P<value>.*);"
    replace: "console.log({{value}});\n"

  # arrow functions
  - trigger: "fn;"
    replace: "($|$)=>{return }"

  # Static arrow functions
  - trigger: ".reduce"
    replace: ".reduce((acc,curr,idx,arr)=>{return acc + curr$|$}, 0)"
  - trigger: ".sort"
    replace: ".sort((a,b)=>{return a-b$|$})"
  - trigger: ".map"
    replace: ".map((elem, idx, arr)=>{return $|$})"
  - trigger: ".filter"
    replace: ".filter((elem, idx, arr)=>{return true$|$})"

  # HTML DOM Stuff
  # - regex: "tag(?P<tagName>.*);"
  #   replace: "<{{tagName}}> < {{tagName}}>"
