# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # NOTE: I left off traling } in most/all commands as most text editors automatically add it in.

  # - trigger: "for;"
  #   replace: "for(let i = 0; i < .length; i++){\n$|$"
  # - trigger: "for;"
  #   replace: "for(let j = 0; j < .length; j++){\n$|$"
  # - trigger: "for;"
  #   replace: "for ([key, value] of Object.entries(obj)) {\n"

  # Static for loops
  - trigger: "fori;"
    replace: "for(let i = 0; i < .length; i++){\n$|$"
  - trigger: "forj;"
    replace: "for(let j = 0; j < .length; j++){\n$|$"
  - trigger: "fork;"
    replace: "for(let k = 0; k < .length; k++){\n$|$"
  - trigger: "forobj;"
    replace: "for ([key, value] of Object.entries()) {\n"

  # Paramterized forloops
  # e.g fori,arrayName;
  # - regex: "forobj(?P<array>.*);" # Dediced this was too many paramters
  # replace: "for ([key, value] of Object.entries({{array}})) {\n"
  # - regex: "forreg(?P<idx>.*),(?P<array>.*);"  # Dediced this was too many paramters
  #   replace: "for(let {{idx}} = 0; {{idx}} < {{array}}.length; {{idx}}++){\n$|$"
  - regex: "fori,(?P<array>.*);"
    replace: "for(let i = 0; i < {{array}}.length; i++){\n$|$"
  - regex: "forj,(?P<array>.*);"
    replace: "for(let j = 0; j < {{array}}.length; j++){\n$|$"
  - regex: "fork,(?P<array>.*);"
    replace: "for(let k = 0; k < {{array}}.length; k++){\n$|$"
  - regex: "forobj,(?P<array>.*);"
    replace: "for ([key, value] of Object.entries({{array}})) {\n"

  # Static if/else
  - trigger: "if;"
    replace: "if($|$){\n"
  - trigger: "elseif;"
    replace: "else if($|$){\n\n"
  - trigger: "else;"
    replace: "else{\n$|$\n"
  - trigger: "tern;"
    replace: "($|$)?  : "
  # - regex: "if,(?P<array>.*);"
  #   replace: "for(let i = 0; i < {{array}}.length; i++){\n$|$"

  # Static try/catch
  - trigger: "try;"
    replace: "try {\n"
  - trigger: "catch;"
    replace: "catch (error) {\nconsole.error(error);"

  # Static logger
  - trigger: "con;"
    replace: "console.log($|$)"
  - trigger: "console;"
    replace: "console.log($|$)"
  - trigger: "log;"
    replace: "console.log($|$)"

  # Paramterized arrow functions
  # e.g fn3,a,b,c;
  - regex: "fn1,(?P<person0>.*);"
    replace: "({{person0}})=>{return }"
  - regex: "fn2,(?P<person0>.*),(?P<person1>.*);"
    replace: "({{person0}},{{person1}})=>{return }"
  - regex: "fn3,(?P<person0>.*),(?P<person1>.*),(?P<person2>.*);"
    replace: "({{person0}},{{person1}},{{person2}})=>{return }"
  - regex: "fn4,(?P<person0>.*),(?P<person1>.*),(?P<person2>.*),(?P<person3>.*);"
    replace: "({{person0}},{{person1}},{{person2}},{{person3}})=>{return }"
  - trigger: "function;"
    replace: "function(){\n"

  # Static arrow functions
  - trigger: "fnreduce;"
    replace: "(acc,curr,idx,arr)=>{return acc + curr}"
  - trigger: "fnacc;"
    replace: "(acc,curr,idx,arr)=>{return acc + curr}"
  - trigger: "fnsum;"
    replace: "(acc,curr,idx,arr)=>{return acc + curr}"
  - trigger: "fnacend;"
    replace: "(a,b)=>{return a-b}"
  - trigger: "fndecend;"
    replace: "(a,b)=>{return a-b}"

  # HTML DOM Stuff
  - regex: "tag(?P<person0>.*);"
    replace: "<{{person0}}>$|$</{{person0}}>"
